In [1]:
import pandas as pd
import numpy as np

In [2]:
dct = {'col1':[1,1,1,1],
       'col2':[1,2,3,4],
       'col3':[0,0,0,0]}

In [6]:
dct

{'col1': [1, 1, 1, 1], 'col2': [1, 2, 3, 4], 'col3': [0, 0, 0, 0]}

In [5]:
for i in dct.values():
    print(i)

[1, 1, 1, 1]
[1, 2, 3, 4]
[0, 0, 0, 0]


In [7]:
df=pd.DataFrame(dct)

In [8]:
df

col1  col2  col3
0     1     1     0
1     1     2     0
2     1     3     0
3     1     4     0

In [9]:
df.std()   # std of df

col1    0.000000
col2    1.290994
col3    0.000000
dtype: float64

In [ ]:
# col and col2 has no std means they are not significatant(usefull) col 

In [10]:
from sklearn.feature_selection import VarianceThreshold

## .fit_transform()

In [15]:
var =VarianceThreshold()

info_col  = var.fit_transform(df)

In [16]:
info_col  # it see that significant data 

array([[1],
       [2],
       [3],
       [4]], dtype=int64)

In [21]:
new_df = pd.DataFrame(info_col , columns=["col_1"])

In [22]:
new_df

col_1
0      1
1      2
2      3
3      4

### another method which wll give us significant col data interm of true or false 

## .fit()

In [23]:
imp_col = var.fit(df)

In [24]:
imp_col

VarianceThreshold()

In [25]:
imp_col.get_support()

array([False,  True, False])

In [26]:
df

col1  col2  col3
0     1     1     0
1     1     2     0
2     1     3     0
3     1     4     0

In [27]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [28]:
useful_col_var   =  df.columns[imp_col.get_support()== True]

In [29]:
useful_col_var    # we get imp col info

Index(['col2'], dtype='object')

In [31]:
# we can get useless col info also 

not_use_col = df.columns[imp_col.get_support() == False]

In [32]:
not_use_col

Index(['col1', 'col3'], dtype='object')

In [37]:
df

col1  col2  col3
0     1     1     0
1     1     2     0
2     1     3     0
3     1     4     0

In [38]:
df.drop(not_use_col , axis=1 , inplace=True)

In [39]:
df

col2
0     1
1     2
2     3
3     4

In [5]:
# Importing libraries
from sklearn.datasets import fetch_openml
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import seaborn as sns


In [6]:
df = pd.read_csv("clean.csv")

In [7]:
df

Unnamed: 0      ID  var3  var15  imp_ent_var16_ult1  \
0               0       1     2     23                 0.0   
1               1       3     2     34                 0.0   
2               2       4     2     23                 0.0   
3               3       8     2     37                 0.0   
4               4      10     2     39                 0.0   
...           ...     ...   ...    ...                 ...   
76015       76015  151829     2     48                 0.0   
76016       76016  151830     2     39                 0.0   
76017       76017  151835     2     23                 0.0   
76018       76018  151836     2     25                 0.0   
76019       76019  151838     2     46                 0.0   

       imp_op_var39_comer_ult1  imp_op_var40_efect_ult1  imp_sal_var16_ult1  \
0                          0.0                      0.0                 0.0   
1                          0.0                      0.0                 0.0   
2                          0.0                      0.0                 0.0   
3                        195.0                      0.0                 0.0   
4                          0.0                      0.0                 0.0   
...                        ...                      ...                 ...   
76015                      0.0                      0.0                 0.0   
76016                      0.0                      0.0                 0.0   
76017                      0.0                      0.0                 0.0   
76018                      0.0                      0.0                 0.0   
76019                      0.0                      0.0                 0.0   

       ind_var2_0  ind_var2  ...  imp_trasp_var33_out_hace3  num_var2_0_ult1  \
0               0         0  ...                          0                0   
1               0         0  ...                          0                0   
2               0         0  ...                          0                0   
3               0         0  ...                          0                0   
4               0         0  ...                          0                0   
...           ...       ...  ...                        ...              ...   
76015           0         0  ...                          0                0   
76016           0         0  ...                          0                0   
76017           0         0  ...                          0                0   
76018           0         0  ...                          0                0   
76019           0         0  ...                          0                0   

       num_var2_ult1  num_reemb_var13_hace3  num_reemb_var33_hace3  \
0                  0                      0                      0   
1                  0                      0                      0   
2                  0                      0                      0   
3                  0                      0                      0   
4                  0                      0                      0   
...              ...                    ...                    ...   
76015              0                      0                      0   
76016              0                      0                      0   
76017              0                      0                      0   
76018              0                      0                      0   
76019              0                      0                      0   

       num_trasp_var17_out_hace3  num_trasp_var33_out_hace3  saldo_var2_ult1  \
0                              0                          0                0   
1                              0                          0                0   
2                              0                          0                0   
3                              0                          0                0   
4                              0                          0                0   
...                          ..

In [9]:
df.isnull().sum()

Unnamed: 0                       0
ID                               0
var3                             0
var15                            0
imp_ent_var16_ult1               0
imp_op_var39_comer_ult1          0
imp_op_var40_efect_ult1          0
imp_sal_var16_ult1               0
ind_var2_0                       0
ind_var2                         0
ind_var6_0                       0
ind_var13_medio_0                0
ind_var17_0                      0
ind_var18_0                      0
ind_var19                        0
ind_var27_0                      0
ind_var28_0                      0
ind_var28                        0
ind_var27                        0
ind_var34_0                      0
ind_var39_0                      0
ind_var41                        0
ind_var46_0                      0
ind_var46                        0
num_var27_0                      0
num_var28_0                      0
num_var28                        0
num_var27                        0
num_var41           

In [10]:
from sklearn.feature_selection import VarianceThreshold

In [11]:
var = VarianceThreshold()

## .fit()

In [12]:
info_col =var.fit(df)

In [13]:
info_col

VarianceThreshold()

In [14]:
info_col.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True, False, False, False,
       False,  True,  True, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
        True,  True, False, False,  True,  True, False,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False,  True])

In [15]:
df.columns

Index(['Unnamed: 0', 'ID', 'var3', 'var15', 'imp_ent_var16_ult1',
       'imp_op_var39_comer_ult1', 'imp_op_var40_efect_ult1',
       'imp_sal_var16_ult1', 'ind_var2_0', 'ind_var2', 'ind_var6_0',
       'ind_var13_medio_0', 'ind_var17_0', 'ind_var18_0', 'ind_var19',
       'ind_var27_0', 'ind_var28_0', 'ind_var28', 'ind_var27', 'ind_var34_0',
       'ind_var39_0', 'ind_var41', 'ind_var46_0', 'ind_var46', 'num_var27_0',
       'num_var28_0', 'num_var28', 'num_var27', 'num_var41', 'num_var46_0',
       'num_var46', 'saldo_var5', 'saldo_var28', 'saldo_var27', 'saldo_var41',
       'saldo_var46', 'delta_imp_aport_var33_1y3', 'delta_imp_reemb_var13_1y3',
       'imp_amort_var18_hace3', 'imp_amort_var34_hace3', 'imp_var7_emit_ult1',
       'imp_var7_recib_ult1', 'imp_reemb_var13_hace3', 'imp_reemb_var17_hace3',
       'imp_reemb_var33_hace3', 'imp_trasp_var17_in_hace3',
       'imp_trasp_var17_out_hace3', 'imp_trasp_var33_out_hace3',
       'num_var2_0_ult1', 'num_var2_ult1', 'num_reemb_var1

In [16]:
not_use_columns =df.columns[info_col.get_support()== False]

In [17]:
df.drop( not_use_columns , axis=1 , inplace= True )

In [18]:
df

Unnamed: 0      ID  var3  var15  imp_ent_var16_ult1  \
0               0       1     2     23                 0.0   
1               1       3     2     34                 0.0   
2               2       4     2     23                 0.0   
3               3       8     2     37                 0.0   
4               4      10     2     39                 0.0   
...           ...     ...   ...    ...                 ...   
76015       76015  151829     2     48                 0.0   
76016       76016  151830     2     39                 0.0   
76017       76017  151835     2     23                 0.0   
76018       76018  151836     2     25                 0.0   
76019       76019  151838     2     46                 0.0   

       imp_op_var39_comer_ult1  imp_op_var40_efect_ult1  imp_sal_var16_ult1  \
0                          0.0                      0.0                 0.0   
1                          0.0                      0.0                 0.0   
2                          0.0                      0.0                 0.0   
3                        195.0                      0.0                 0.0   
4                          0.0                      0.0                 0.0   
...                        ...                      ...                 ...   
76015                      0.0                      0.0                 0.0   
76016                      0.0                      0.0                 0.0   
76017                      0.0                      0.0                 0.0   
76018                      0.0                      0.0                 0.0   
76019                      0.0                      0.0                 0.0   

       ind_var6_0  ind_var13_medio_0  ...  ind_var34_0  ind_var39_0  \
0               0                  0  ...            0            1   
1               0                  0  ...            0            1   
2               0                  0  ...            0            1   
3               0                  0  ...            0            1   
4               0                  0  ...            0            1   
...           ...                ...  ...          ...          ...   
76015           0                  0  ...            0            1   
76016           0                  0  ...            0            1   
76017           0                  0  ...            0            1   
76018           0                  0  ...            0            1   
76019           0                  0  ...            0            1   

       saldo_var5  delta_imp_aport_var33_1y3  delta_imp_reemb_var13_1y3  \
0            0.00                        0.0                          0   
1            0.00                        0.0                          0   
2            3.00                        0.0                          0   
3           70.62                        0.0                          0   
4            0.00                        0.0                          0   
...           ...                        ...                        ...   
76015        0.00                        0.0                          0   
76016        0.00                        0.0                          0   
76017        3.00                        0.0                          0   
76018        3.00                        0.0                          0   
76019        0.00                        0.0                          0   

       imp_var7_emit_ult1  imp_var7_recib_ult1  imp_reemb_var17_hace3  \
0                     0.0                  0.0                    0.0   
1                     0.0                  0.0                    0.0   
2                     0.0                  0.0                    0.0   
3                     0.0                  0.0                    0.0   
4                     0.0                  0.0                    0.0   
...                   ...                  ...                    ...   
76015                 0.0                  0.0  

In [20]:
df.info()   # you get new data frame with most significant col   # remove id  col 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Unnamed: 0                 76020 non-null  int64  
 1   ID                         76020 non-null  int64  
 2   var3                       76020 non-null  int64  
 3   var15                      76020 non-null  int64  
 4   imp_ent_var16_ult1         76020 non-null  float64
 5   imp_op_var39_comer_ult1    76020 non-null  float64
 6   imp_op_var40_efect_ult1    76020 non-null  float64
 7   imp_sal_var16_ult1         76020 non-null  float64
 8   ind_var6_0                 76020 non-null  int64  
 9   ind_var13_medio_0          76020 non-null  int64  
 10  ind_var17_0                76020 non-null  int64  
 11  ind_var18_0                76020 non-null  int64  
 12  ind_var19                  76020 non-null  int64  
 13  ind_var34_0                76020 non-null  int

## fit_transform()

In [100]:
selector = VarianceThreshold()

In [101]:
info = selector.fit_transform(df)

In [102]:
info

array([[0.00000000e+00, 1.00000000e+00, 2.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 3.92051700e+04],
       [1.00000000e+00, 3.00000000e+00, 2.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 4.92780300e+04],
       [2.00000000e+00, 4.00000000e+00, 2.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 6.73337700e+04],
       ...,
       [7.60170000e+04, 1.51835000e+05, 2.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 7.40281500e+04],
       [7.60180000e+04, 1.51836000e+05, 2.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 8.42781600e+04],
       [7.60190000e+04, 1.51838000e+05, 2.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.17310979e+05]])